# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
