# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2009-01-01 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock_type',
            field=models.CharField(default=b'opening', max_length=20),
        ),
    ]
