# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20160412_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='location',
            new_name='store_location',
        ),
    ]
