# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20160319_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'product name', max_length=20)),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
