# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_auto_20160322_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(choices=[(b'1', b'Opening Stock'), (b'2', b'Closing stock'), (b'3', b'New stock')], max_length=20),
        ),
    ]
