"""
Django settings for sandd project.

<<<<<<< HEAD
For more information on this file, see
https://docs.djangoproject.com/en/1.6/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.6/ref/settings/
=======
Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
<<<<<<< HEAD
BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.6/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sex+$dfqj0^gd#y&@ntdw%d0dtj=w^2$%qj(jq&#yipv7-*j45'
=======

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fol4-jw6-b5)$*1m2mx$^47vp9u(d4j*14mr^s_m#c@$_)@sro'
>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
TEMPLATE_DEBUG = True

=======
>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
=======
    'adm',
>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
<<<<<<< HEAD
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
=======
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f
)

ROOT_URLCONF = 'sandd.urls'

<<<<<<< HEAD
=======
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f
WSGI_APPLICATION = 'sandd.wsgi.application'


# Database
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.6/ref/settings/#databases
=======
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

<<<<<<< HEAD
# Internationalization
# https://docs.djangoproject.com/en/1.6/topics/i18n/
=======

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD
# https://docs.djangoproject.com/en/1.6/howto/static-files/
=======
# https://docs.djangoproject.com/en/1.8/howto/static-files/
>>>>>>> 8052b7ec016c37e91a9217b06d5337059ac7581f

STATIC_URL = '/static/'
